import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#051424',
        'surface-dim': '#051424',
        'surface-bright': '#2c3a4c',
        'surface-container-lowest': '#010f1f',
        'surface-container-low': '#0d1c2d',
        'surface-container': '#122131',
        'surface-container-high': '#1c2b3c',
        'surface-container-highest': '#273647',
        'on-surface': '#d4e4fa',
        'on-surface-variant': '#c7c4d7',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        'outline': '#908fa0',
        'outline-variant': '#464554',
        'surface-tint': '#c0c1ff',
        'primary': '#c0c1ff',
        'on-primary': '#1000a9',
        'primary-container': '#8083ff',
        'on-primary-container': '#0d0096',
        'inverse-primary': '#494bd6',
        'secondary': '#bdc2ff',
        'on-secondary': '#131e8c',
        'secondary-container': '#2f3aa3',
        'on-secondary-container': '#a8afff',
        'tertiary': '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#00885d',
        'on-tertiary-container': '#000703',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-fixed': '#e0e0ff',
        'secondary-fixed-dim': '#bdc2ff',
        'on-secondary-fixed': '#000767',
        'on-secondary-fixed-variant': '#2f3aa3',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#051424',
        'on-background': '#d4e4fa',
        'surface-variant': '#273647',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'stack-sm': '0.5rem',
        'gutter': '1.5rem',
        'margin-page': '2rem',
        'stack-lg': '2rem',
        'stack-md': '1rem',
        'container-max': '1280px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'mono-sm': ['JetBrains Mono', 'monospace'],
        'headline-xl': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'mono-base': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'mono-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-base': ['14px', { lineHeight: '20px', fontWeight: '450' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
